"""empty message

Revision ID: 2316f4306015
Revises: eff378f8268f
Create Date: 2020-12-04 13:36:59.039350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2316f4306015'
down_revision = 'eff378f8268f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
