"""empty message

Revision ID: 3f51ee0bdc4a
Revises: 61d9d71d59ad
Create Date: 2020-12-05 10:24:16.144040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f51ee0bdc4a'
down_revision = '61d9d71d59ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('params', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_params_id'), 'params', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_params_id'), table_name='params')
    op.drop_column('params', 'id')
    # ### end Alembic commands ###
