"""empty message

Revision ID: 41480d7a9dd4
Revises: d9732ffca32f
Create Date: 2020-12-04 17:29:17.647535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41480d7a9dd4'
down_revision = 'd9732ffca32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('params')
    # ### end Alembic commands ###
