"""empty message

Revision ID: 7d01d330173a
Revises: 2316f4306015
Create Date: 2020-12-04 13:48:48.026140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d01d330173a'
down_revision = '2316f4306015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
