"""empty message

Revision ID: d9732ffca32f
Revises: 7d01d330173a
Create Date: 2020-12-04 14:42:22.088335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9732ffca32f'
down_revision = '7d01d330173a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
