"""empty message

Revision ID: efcad3028613
Revises: 3f51ee0bdc4a
Create Date: 2020-12-05 10:40:30.237388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcad3028613'
down_revision = '3f51ee0bdc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Params_id'), 'Params', ['id'], unique=False)
    op.drop_index('ix_params_id', table_name='params')
    op.drop_table('params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_index('ix_params_id', 'params', ['id'], unique=False)
    op.drop_index(op.f('ix_Params_id'), table_name='Params')
    op.drop_table('Params')
    # ### end Alembic commands ###
