"""empty message

Revision ID: f15b815f8bef
Revises: efcad3028613
Create Date: 2020-12-06 08:59:14.487316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15b815f8bef'
down_revision = 'efcad3028613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_search', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_search'], ['Params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Counter_id'), 'Counter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Counter_id'), table_name='Counter')
    op.drop_table('Counter')
    # ### end Alembic commands ###
